apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: idshoominga/users-yyang27-jx-quickstart-demo-jx-quickstart-node-http-demo1
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/{{.IMAGE_NAME}}:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/{{.IMAGE_NAME}}:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: users-yyang27-jx-quickstart-demo-jx-quickstart-node-http-demo1
        chartPath: charts/users-yyang27-jx-quickstart-demo-jx-quickstart-node-http-demo1
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/{{.IMAGE_NAME}}'
          image.tag: '{{.DIGEST_HEX}}'
